### ISSUE TITLE
Error (v1.0 errors when SELinux is enforcing. Fixed in v1.1)

### ISSUE THREAD

**Issue by Alexey71** [jingyu9575/UseRoundIcon#1]
[xposed_error_20170813_180850.log.txt](https://github.com/jingyu9575/UseRoundIcon/files/1220529/xposed_error_20170813_180850.log.txt)

**Comment by jingyu9575** [comment]
It seems that SELinux caused this problem. v1.1 tried fixing it. Could you try the new version and see if it works?

**Comment by Alexey71** [comment]
Errors are gone. But I do not understand how the module works. Nothing changes. I use nova launcher
[xposed_error_20170814_095220.log.txt](https://github.com/jingyu9575/UseRoundIcon/files/1221460/xposed_error_20170814_095220.log.txt)

**Comment by jingyu9575** [comment]
> how the module works

In Xposed Installer -> Modules -> enter this module, there is a checkbox to set whether round icons are used. Restart phone to take effect.

> Nothing changes

Look at the icon of this module "Use Round Icons" in Settings -> Apps, or Xposed Installer -> Modules. Is this icon in your preferred style?

Normal: ![normal icon](https://user-images.githubusercontent.com/8923139/29274253-cd1e8cde-8139-11e7-876b-35a1e8ebb7b9.png)  Round: ![ic_launcher_round](https://user-images.githubusercontent.com/8923139/29274274-dec0cb6e-8139-11e7-898a-6be7cf838922.png)

If so, the module works and the launcher's icon cache needs to be cleared. For Nova Launcher (latest version), Nova Settings -> Look & feel -> change the icon theme to another -> return to home screen -> change back the icon theme.

**Comment by Alexey71** [comment]
Working. I love the normal icons. Thank you
